### ISSUE TITLE
robot 脚本需要更新

### ISSUE THREAD

**Issue by TrevDk** [uzdz/114_robot#2]
目前会返回空
<img width="524" alt="image" src="https://github.com/uzdz/114_robot/assets/39556927/920011c8-4e39-4d4e-b28e-5d1d739971e8">

**Comment by uzdz** [comment]
<img width="1487" alt="image" src="https://github.com/uzdz/114_robot/assets/28328355/35e911d2-5ee0-4fd2-9c5d-8fe48be6ed87">

我这边没问题呀，辛苦把输入参数发一下吧，关键信息可以打马赛克 :)

**Comment by uzdz** [comment]
不过我猜测是你的`token`设置错误了。

<img width="1093" alt="image" src="https://github.com/uzdz/114_robot/assets/28328355/276cd9ca-f54c-42ec-8061-70e1fc52e0c0">

找到`cmi-user-ticket`的`key`和`value`，然后等待程序进入此步骤时：

<img width="629" alt="image" src="https://github.com/uzdz/114_robot/assets/28328355/0cb094dc-048b-4f1c-b522-aedc34a90c6b">

键入`cmi-user-ticket=xxx`，`xxx`的值为你自己的值即可。

**Comment by uzdz** [comment]
如果有问题再重新打开issues，当前先关闭了 :)

**Comment by TrevDk** [comment]
确实是我的问题，我在mac的chrome上复制的token不知道为啥错了，换Windows就好了
