### ISSUE TITLE
大佬 可以添加一下 医生筛选吗

### ISSUE THREAD

**Issue by CN-Sucre** [uzdz/114_robot#3]
如题

**Comment by uzdz** [comment]
刚刚看了下114的接口返回情况，因为对方只返回了日期和是否有号。

<img width="1036" alt="image" src="https://github.com/uzdz/114_robot/assets/28328355/ee61405d-7b9d-4ac6-8de1-30106e082843">

所以我评估是需要些时间开发的，但目前因为我有其他的事情抽不出身，所以暂时无法支持此功能，十分抱歉哈。

我也看了下，其实对接一下114的`detail`接口，做下过滤即可，所以如果您有意愿可以支持此功能，提交Pull Request。

<img width="949" alt="image" src="https://github.com/uzdz/114_robot/assets/28328355/e41f92f1-81b6-458a-aa2b-67102e5a036e">

目前先关闭此Issues了，感谢反馈，如后续支持了此功能，会在此Issues发布评论。
