### ISSUE TITLE
什么是将key和value用=连接起来呀？

### ISSUE THREAD

**Issue by ww249** [uzdz/114_robot#4]
key是什么？在哪里呀？太小白了，麻烦大佬可以说的稍微细致一点点嘛

**Comment by uzdz** [comment]
<img width="805" alt="捕获" src="https://github.com/uzdz/114_robot/assets/28328355/caecdaea-b3e9-4abf-8b98-b17b56ce56f6">

这其中name就是key，然后name后面的值就是value，你注意看我的红色线，然后把他俩通过等于号(=)拼起来就可以了。

**Comment by ww249** [comment]
哦哦感谢感谢，被自己蠢到了。但我运行了之后发现，怎么不显示27号的呀？








С??
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "uzdz/114_robot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月20日(星期三) 晚上8:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [uzdz/114_robot] 什么是将key和value用=连接起来呀？ (Issue #4)





  
这其中name就是key，然后name后面的值就是value，你注意看我的红色线，然后把他俩通过等于号(=)拼起来就可以了。

**Comment by uzdz** [comment]
目前只显示最近7天（包含今天）的门诊状态，您明天可以再看下。

Tips：如果对您有帮助，还可以关注start下我的其他开源项目。

**Comment by ww249** [comment]
噢噢好滴，感谢！会给您多加星星的，我还有个疑问就是怎么把webhook加到代码里呀？
我没找到代码里webhook相关的代码。




С??
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "uzdz/114_robot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月20日(星期三) 晚上9:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [uzdz/114_robot] 什么是将key和value用=连接起来呀？ (Issue #4)





 
目前只显示最近7天（包含今天）的门诊状态，您明天可以再看下。
 
Tips：如果对您有帮助，还可以关注start下我的其他开源项目。

**Comment by uzdz** [comment]
![image](https://github.com/uzdz/114_robot/assets/28328355/f6f9e4e8-3d60-4f02-aca4-cf41b6694f44)

目录下有feishu.py和dingding.py，这里面的webhook这个参数值填入机器人群地址即可，目前仅支持这种配置方式。
